# Generated by Django 4.2.10 on 2025-05-03 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='api.UserProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
