# Generated by Django 4.2.10 on 2025-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAccessView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('access_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'chat_access_view',
                'managed': False,
            },
        ),
    ]
