# Generated by Django 4.2.10 on 2025-05-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chataccessview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
        ),
    ]
