# Generated by Django 4.2.10 on 2025-05-04

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_chat_project'),
    ]

    operations = [
        # Add 'level' field to Role
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=5),
        ),

        # Create OrganisationChat model
        migrations.CreateModel(
            name='OrganisationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('min_role_level', models.IntegerField(
                    choices=[
                        (2, 'Core Team Only'),
                        (3, 'Contributors and Above'),
                        (4, 'Family, Friends and Above'),
                        (5, 'Everyone (including Fans)')
                    ],
                    default=5,
                )),
                ('organisation', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.organisation'
                )),
            ],
        ),

        # Add organisation_chat FK to Chat
        migrations.AddField(
            model_name='chat',
            name='organisation_chat',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.organisationchat'
            ),
        ),

        # Make Chat.project optional
        migrations.AlterField(
            model_name='chat',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.project'
            ),
        ),
    ]
