# Generated by Django 4.2.10 on 2025-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_chat_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
