# Generated by Django 4.2.10 on 2025-05-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_role_level'),
        ('api', '0012_alter_chat_view'),
    ]

    operations = [
    ]
