# Generated by Django 4.2.10 on 2025-05-04 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='organisation_chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='min_role_level',
            field=models.IntegerField(choices=[(2, 'Core Team Only'), (3, 'Contributors and Above'), (4, 'Family, Friends and Above'), (5, 'Everyone (including Fans)')], default=5),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Chat', max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
            preserve_default=False,
        ),
    ]
