# Generated by Django 4.2.10 on 2025-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0011_role_level_0012_alter_chat_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationchat',
            name='min_role_level',
            field=models.IntegerField(choices=[(2, 'Core Team Only'), (3, 'Contributors and Above'), (4, 'Family, Friends and Above'), (5, 'Everyone (including Fans)')], default=5),
        ),
    ]
