# Generated by Django 4.2.10 on 2025-05-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='organisation',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrganisationChat',
        ),
    ]
