# Generated by Django 4.2.10 on 2025-05-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_make_song_organisation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='nr',
            field=models.IntegerField(),
        ),
    ]
