# Generated by Django 4.2.10 on 2025-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_song_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='nr',
            field=models.IntegerField(editable=False),
        ),
    ]
