# Generated by Django 4.2.10 on YYYY-MM-DD HH:MM
from django.conf import settings
from django.db import migrations, models

def delete_all_events_and_dependencies(apps, schema_editor):
    """Delete all events and related objects before altering fields"""
    # First handle all models that reference Event
    Timetable = apps.get_model('api', 'Timetable')
    Setlist = apps.get_model('api', 'Setlist')
    
    # Delete these completely as they directly depend on events
    Timetable.objects.all().delete()
    Setlist.objects.all().delete()
    
    # For models with nullable FK to Event, update to null instead of deleting
    Task = apps.get_model('api', 'Task')
    Project = apps.get_model('api', 'Project')
    
    Task.objects.filter(event__isnull=False).update(event=None)
    Project.objects.filter(event__isnull=False).update(event=None)
    
    # Finally delete all events
    Event = apps.get_model('api', 'Event')
    Event.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_seed_status'),
    ]

    operations = [
        # First, delete all events
        migrations.RunPython(
            delete_all_events_and_dependencies,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Drop the original columns
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        
        # Add new columns with DateTimeField type
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default='2025-05-16T09:00:00+00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default='2025-05-16T10:00:00+00:00'),
            preserve_default=False,
        ),
        
        # Create CalendarSubscription model
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='subscription_tokens', to='api.calendar')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='calendar_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]