# Generated by Django 4.2.10 on 2025-05-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chat'),
        ),
    ]
