# Generated by Django 4.2.10 on 2025-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_userproject_unique_together_external_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
