# Generated by Django 4.2.10 on 2025-05-29 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_organisationinvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organisationinvitation',
            name='invited_user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(db_index=True, default='peinlich', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationinvitation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationinvitation',
            unique_together={('organisation', 'invited_user')},
        ),
        migrations.RemoveField(
            model_name='organisationinvitation',
            name='email',
        ),
    ]
