# Generated by Django 4.2.10 on 2025-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_organisationinvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organisationinvitation',
            name='invite_code',
            field=models.CharField(db_index=True, default='hans1234', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='organisationinvitation',
            unique_together={('organisation', 'invite_code')},
        ),
        migrations.RemoveField(
            model_name='organisationinvitation',
            name='invited_user',
        ),
    ]
